name: teacher_dashboard_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Firebase Core - Required for all Firebase services
  firebase_core: ^3.15.2
  
  # Firebase Services
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_crashlytics: ^4.3.10
  firebase_database: ^11.3.10
  firebase_messaging: ^15.2.10
  cloud_functions: ^5.3.10
  
  # Authentication
  google_sign_in: ^7.1.1
  google_sign_in_web: ^1.0.0
  google_identity_services_web: ^0.3.3+1 
  
  # Web support
  web: 1.1.1
  
  # State Management
  provider: ^6.1.2
  
  # Charts and Data Visualization
  fl_chart: ^1.0.0
  
  # UI & Navigation
  go_router: ^16.0.0
  smooth_page_indicator: ^1.2.0+3
  
  # Utilities
  intl: ^0.20.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.2
  
  # File handling
  file_picker: ^10.2.0
  
  # Image caching for performance
  cached_network_image: ^3.4.1
  
  # Video support
  video_player: ^2.8.2
  video_compress: ^3.1.4
  
  # WebRTC for video/voice calling
  flutter_webrtc: ^1.0.0
  permission_handler: ^12.0.1
  
  # Notifications - Re-enabled with desktop support
  flutter_local_notifications: ^17.2.4  # Kept at current version due to device_calendar constraint
  timezone: ^0.9.4  # Pinned due to device_calendar dependency
  
  # Call UI for mobile platforms (iOS CallKit, Android ConnectionService)
  flutter_callkit_incoming: ^2.5.5
  
  # Calendar sync
  device_calendar: ^4.3.3
  icalendar_parser: ^2.1.0  # For iCalendar export
  # ical: ^0.1.3  # For generating iCalendar files - temporarily disabled due to null safety issues
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  rxdart: ^0.28.0
  mcp_toolkit: ^0.2.3

# Dependency overrides to resolve version conflicts
dependency_overrides:
  js: ^0.7.2  # Force to latest version before discontinuation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Development tools
  test: ^1.25.15  # Pinned due to integration_test SDK constraint
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  # flutter_native_splash: ^2.4.6  # Temporarily disabled - causes build issues
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  
  # Code quality tools
  # very_good_analysis: ^7.0.0  # Too strict for this project
  # dart_code_metrics: ^5.7.4  # Conflicts with other dependencies
  import_sorter: ^4.6.0
  
  # Testing tools
  mockito: ^5.5.0
  faker: ^2.2.0
  # golden_toolkit: ^0.15.0  # Discontinued package - needs replacement
  # patrol: ^3.15.0  # Temporarily disabled - causes build issues
  
  # CI/CD tools
  flutter_gen_runner: ^5.9.1
  # flutter_version: ^0.3.2  # Package discontinued, needs replacement

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Custom scripts for development workflow
scripts:
  # Code quality
  analyze: flutter analyze
  format: dart format . --line-length=80
  format:check: dart format . --line-length=80 --set-exit-if-changed
  lint: flutter analyze && dart format . --set-exit-if-changed
  fix: dart fix --apply
  
  # Testing
  test: flutter test
  test:unit: flutter test test/
  test:widget: flutter test test/widgets/
  test:integration: flutter test integration_test
  test:coverage: flutter test --coverage
  test:golden: flutter test --update-goldens
  
  # Build commands
  build:apk: flutter build apk --release
  build:ios: flutter build ios --release
  build:web: flutter build web --release
  build:windows: flutter build windows --release
  build:macos: flutter build macos --release
  build:linux: flutter build linux --release
  
  # Development tools
  clean: flutter clean && flutter pub get
  deps: flutter pub get
  deps:upgrade: flutter pub upgrade --major-versions
  deps:outdated: flutter pub outdated
  
  # Code generation
  generate: flutter pub run build_runner build --delete-conflicting-outputs
  generate:watch: flutter pub run build_runner watch --delete-conflicting-outputs
  
  # Import sorting
  sort: flutter pub run import_sorter:main
  
  # Pre-commit checks
  pre-commit: flutter analyze && dart format . --set-exit-if-changed && flutter test
  
  # CI/CD helpers
  ci:setup: flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
  ci:test: flutter test --coverage --test-randomize-ordering-seed random
  ci:analyze: flutter analyze --no-fatal-infos

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
