name = 'fermi-plus'
main = "src/index.js"
compatibility_date = "2025-09-01"
route = "https://fermi-plus.com/*"

[assets]
directory = "./build/web"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability.logs]
enabled = true

# Build command for local reference (not used by Cloudflare)
# Run this before deploying: flutter pub get && flutter build web --release
