/// Student model for managing student profiles and enrollment data.
///
/// This module contains the data model for students, representing
/// learners enrolled in classes within the education management system.
library;

import 'package:cloud_firestore/cloud_firestore.dart';

/// Core student model representing a learner in the system.
///
/// This model encapsulates all student-specific data, including:
/// - Personal information (name, email, grade)
/// - Class enrollments
/// - Parent/guardian contact information
/// - Profile metadata
///
/// The Student model is separate from UserModel to allow:
/// - Teacher-specific views of student data
/// - Enrollment management without full user access
/// - Parent contact information storage
/// - Grade-level specific features
class Student {
  /// Unique identifier for the student record
  final String id;

  /// Associated user ID linking to authentication system
  final String uid;

  /// Student's username for login (generated by teacher)
  final String username;

  /// Temporary password (encrypted, only used before first login)
  final String? temporaryPassword;

  /// Whether the student has claimed their account
  final bool accountClaimed;

  /// Whether the student has changed their password from temporary
  final bool passwordChanged;

  /// Optional backup email for password recovery
  final String? backupEmail;

  /// Student's email address (optional, set after claiming)
  final String? email;

  /// Student's first name
  final String firstName;

  /// Student's last name
  final String lastName;

  /// Display name shown in UI (typically "FirstName LastName")
  final String displayName;

  /// Current grade level (1-12 for K-12 systems)
  final int gradeLevel;

  /// Optional parent/guardian email for notifications
  final String? parentEmail;

  /// List of class IDs the student is enrolled in
  final List<String> classIds;

  /// Optional URL to student's profile photo
  final String? photoURL;

  /// Timestamp when the student record was created
  final DateTime createdAt;

  /// Timestamp of last update to student record
  final DateTime updatedAt;

  /// Whether the student account is active
  final bool isActive;

  /// Flexible metadata for additional student information
  final Map<String, dynamic>? metadata;

  Student({
    required this.id,
    required this.uid,
    required this.username,
    this.temporaryPassword,
    this.accountClaimed = false,
    this.passwordChanged = false,
    this.backupEmail,
    this.email,
    required this.firstName,
    required this.lastName,
    required this.displayName,
    required this.gradeLevel,
    this.parentEmail,
    required this.classIds,
    this.photoURL,
    required this.createdAt,
    required this.updatedAt,
    this.isActive = true,
    this.metadata,
  });

  /// Gets the student's full name by combining first and last names.
  /// @return Full name as "FirstName LastName"
  String get fullName => '$firstName $lastName';

  /// Gets the number of classes the student is enrolled in.
  /// @return Count of enrolled classes
  int get classCount => classIds.length;

  /// Factory constructor to create Student from Firestore document.
  ///
  /// Handles data parsing with safe defaults including:
  /// - Null-safe timestamp conversions with fallback to current time
  /// - Default values for required fields
  /// - List casting for class IDs
  /// - Optional field preservation
  ///
  /// @param doc Firestore document snapshot containing student data
  /// @return Parsed Student instance
  factory Student.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    return Student(
      id: doc.id,
      uid: data['uid'] ?? '',
      username: data['username'] ?? '',
      temporaryPassword: data['temporaryPassword'],
      accountClaimed: data['accountClaimed'] ?? false,
      passwordChanged: data['passwordChanged'] ?? false,
      backupEmail: data['backupEmail'],
      email: data['email'],
      firstName: data['firstName'] ?? '',
      lastName: data['lastName'] ?? '',
      displayName: data['displayName'] ?? '',
      gradeLevel: data['gradeLevel'] ?? 0,
      parentEmail: data['parentEmail'],
      classIds: List<String>.from(data['classIds'] ?? []),
      photoURL: data['photoURL'],
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      updatedAt: (data['updatedAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      isActive: data['isActive'] ?? true,
      metadata: data['metadata'],
    );
  }

  /// Converts the Student instance to a Map for Firestore storage.
  ///
  /// Note: DateTime fields are stored directly without conversion
  /// to Timestamp, which may need adjustment based on Firestore
  /// configuration requirements.
  ///
  /// @return Map containing all student data for Firestore persistence
  Map<String, dynamic> toFirestore() {
    return {
      'uid': uid,
      'username': username,
      'temporaryPassword': temporaryPassword,
      'accountClaimed': accountClaimed,
      'passwordChanged': passwordChanged,
      'backupEmail': backupEmail,
      'email': email,
      'firstName': firstName,
      'lastName': lastName,
      'displayName': displayName,
      'gradeLevel': gradeLevel,
      'parentEmail': parentEmail,
      'classIds': classIds,
      'photoURL': photoURL,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
      'isActive': isActive,
      'metadata': metadata,
    };
  }

  /// Creates a copy of the Student with updated fields.
  ///
  /// Follows the immutable data pattern for state management.
  /// Useful for:
  /// - Updating student information
  /// - Managing class enrollments
  /// - Modifying grade level or status
  ///
  /// All parameters are optional - only provided fields will be updated.
  ///
  /// @return New Student instance with updated fields
  Student copyWith({
    String? id,
    String? uid,
    String? username,
    String? temporaryPassword,
    bool? accountClaimed,
    bool? passwordChanged,
    String? backupEmail,
    String? email,
    String? firstName,
    String? lastName,
    String? displayName,
    int? gradeLevel,
    String? parentEmail,
    List<String>? classIds,
    String? photoURL,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isActive,
    Map<String, dynamic>? metadata,
  }) {
    return Student(
      id: id ?? this.id,
      uid: uid ?? this.uid,
      username: username ?? this.username,
      temporaryPassword: temporaryPassword ?? this.temporaryPassword,
      accountClaimed: accountClaimed ?? this.accountClaimed,
      passwordChanged: passwordChanged ?? this.passwordChanged,
      backupEmail: backupEmail ?? this.backupEmail,
      email: email ?? this.email,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      displayName: displayName ?? this.displayName,
      gradeLevel: gradeLevel ?? this.gradeLevel,
      parentEmail: parentEmail ?? this.parentEmail,
      classIds: classIds ?? this.classIds,
      photoURL: photoURL ?? this.photoURL,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isActive: isActive ?? this.isActive,
      metadata: metadata ?? this.metadata,
    );
  }
}
