// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac',
    appId: '1:218352465432:web:6e1c0fa4f21416df38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac',
    appId: '1:218352465432:android:a7d591b9db6bef6038b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac',
    appId: '1:218352465432:ios:5lt4mte28dqof4ae3igmi6m8i261jh99',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    iosBundleId: 'com.teacherdashboard.teacherDashboardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac',
    appId: '1:218352465432:ios:5lt4mte28dqof4ae3igmi6m8i261jh99',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    iosBundleId: 'com.teacherdashboard.teacherDashboardFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac',
    appId: '1:218352465432:web:6e1c0fa4f21416df38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac',
    appId: '1:218352465432:web:6e1c0fa4f21416df38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
  );
}