// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl_36NLwN3O9POk5SMD86jX_LGY1IDFrM',
    appId: '1:218352465432:web:4254a98138547b7138b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    databaseURL:
        'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    measurementId: 'G-VWHGE5G997',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac',
    appId: '1:218352465432:android:a7d591b9db6bef6038b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    databaseURL:
        'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD52btw4TrLb1G6otPJTSr2FXRukwDhB-k',
    appId: '1:218352465432:ios:33fe51117562f8d938b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    databaseURL:
        'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    androidClientId:
        '218352465432-2kmehjp1b5g8r4n5t2ul09t5gqiuajop.apps.googleusercontent.com',
    iosClientId:
        '218352465432-g06upomjmavqesl9tf51fnn7crga6jgk.apps.googleusercontent.com',
    iosBundleId: 'com.academic-tools.fermi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl_36NLwN3O9POk5SMD86jX_LGY1IDFrM',
    appId: '1:218352465432:web:05826e2607e681cd38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    databaseURL:
        'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    measurementId: 'G-ZE9KXELPFY',
  );

  // Added for desktop support parity. Using iOS configuration for macOS by default.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD52btw4TrLb1G6otPJTSr2FXRukwDhB-k',
    appId: '1:218352465432:ios:33fe51117562f8d938b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    databaseURL:
        'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    iosClientId:
        '218352465432-g06upomjmavqesl9tf51fnn7crga6jgk.apps.googleusercontent.com',
    iosBundleId: 'com.academic-tools.fermi',
  );

  // Added for Linux desktop development; mirrors Web defaults.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBl_36NLwN3O9POk5SMD86jX_LGY1IDFrM',
    appId: '1:218352465432:web:05826e2607e681cd38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    databaseURL:
        'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    measurementId: 'G-ZE9KXELPFY',
  );
}
