// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY',
        defaultValue: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_WEB',
        defaultValue: '1:218352465432:web:6e1c0fa4f21416df38b56d'),
    messagingSenderId: const String.fromEnvironment(
        'FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '218352465432'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'teacher-dashboard-flutterfire'),
    authDomain: const String.fromEnvironment('FIREBASE_AUTH_DOMAIN',
        defaultValue: 'teacher-dashboard-flutterfire.firebaseapp.com'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'teacher-dashboard-flutterfire.firebasestorage.app'),
    databaseURL: const String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com'),
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY',
        defaultValue: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_ANDROID',
        defaultValue: '1:218352465432:android:a7d591b9db6bef6038b56d'),
    messagingSenderId: const String.fromEnvironment(
        'FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '218352465432'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'teacher-dashboard-flutterfire'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'teacher-dashboard-flutterfire.firebasestorage.app'),
    databaseURL: const String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com'),
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY',
        defaultValue: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_IOS',
        defaultValue: '1:218352465432:ios:5lt4mte28dqof4ae3igmi6m8i261jh99'),
    messagingSenderId: const String.fromEnvironment(
        'FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '218352465432'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'teacher-dashboard-flutterfire'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'teacher-dashboard-flutterfire.firebasestorage.app'),
    databaseURL: const String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com'),
    iosBundleId: const String.fromEnvironment('IOS_BUNDLE_ID',
        defaultValue: 'com.teacherdashboard.teacherDashboardFlutter'),
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY',
        defaultValue: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_IOS',
        defaultValue: '1:218352465432:ios:5lt4mte28dqof4ae3igmi6m8i261jh99'),
    messagingSenderId: const String.fromEnvironment(
        'FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '218352465432'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'teacher-dashboard-flutterfire'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'teacher-dashboard-flutterfire.firebasestorage.app'),
    databaseURL: const String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com'),
    iosBundleId: const String.fromEnvironment('IOS_BUNDLE_ID',
        defaultValue: 'com.teacherdashboard.teacherDashboardFlutter'),
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY',
        defaultValue: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_WEB',
        defaultValue: '1:218352465432:web:6e1c0fa4f21416df38b56d'),
    messagingSenderId: const String.fromEnvironment(
        'FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '218352465432'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'teacher-dashboard-flutterfire'),
    authDomain: const String.fromEnvironment('FIREBASE_AUTH_DOMAIN',
        defaultValue: 'teacher-dashboard-flutterfire.firebaseapp.com'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'teacher-dashboard-flutterfire.firebasestorage.app'),
    databaseURL: const String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com'),
  );

  static FirebaseOptions linux = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY',
        defaultValue: 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac'),
    appId: const String.fromEnvironment('FIREBASE_APP_ID_WEB',
        defaultValue: '1:218352465432:web:6e1c0fa4f21416df38b56d'),
    messagingSenderId: const String.fromEnvironment(
        'FIREBASE_MESSAGING_SENDER_ID',
        defaultValue: '218352465432'),
    projectId: const String.fromEnvironment('FIREBASE_PROJECT_ID',
        defaultValue: 'teacher-dashboard-flutterfire'),
    authDomain: const String.fromEnvironment('FIREBASE_AUTH_DOMAIN',
        defaultValue: 'teacher-dashboard-flutterfire.firebaseapp.com'),
    storageBucket: const String.fromEnvironment('FIREBASE_STORAGE_BUCKET',
        defaultValue: 'teacher-dashboard-flutterfire.firebasestorage.app'),
    databaseURL: const String.fromEnvironment('FIREBASE_DATABASE_URL',
        defaultValue:
            'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com'),
  );
}
