// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Get API key from environment variables with fallback for local development
  static String get _apiKey {
    const key = String.fromEnvironment('FIREBASE_API_KEY');
    // Only use fallback in debug mode for local development
    if (key.isEmpty && kDebugMode) {
      // This fallback should only be used in development
      // In production, the API key must be provided via environment variables
      return 'AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac';
    }
    if (key.isEmpty) {
      throw Exception('FIREBASE_API_KEY environment variable is not set');
    }
    return key;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:218352465432:web:6e1c0fa4f21416df38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    databaseURL: 'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:218352465432:android:a7d591b9db6bef6038b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    databaseURL: 'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:218352465432:ios:5lt4mte28dqof4ae3igmi6m8i261jh99',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    databaseURL: 'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    iosBundleId: 'com.teacherdashboard.teacherDashboardFlutter',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:218352465432:ios:5lt4mte28dqof4ae3igmi6m8i261jh99',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    databaseURL: 'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
    iosBundleId: 'com.teacherdashboard.teacherDashboardFlutter',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:218352465432:web:6e1c0fa4f21416df38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    databaseURL: 'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
  );

  static FirebaseOptions get linux => FirebaseOptions(
    apiKey: _apiKey,
    appId: '1:218352465432:web:6e1c0fa4f21416df38b56d',
    messagingSenderId: '218352465432',
    projectId: 'teacher-dashboard-flutterfire',
    authDomain: 'teacher-dashboard-flutterfire.firebaseapp.com',
    storageBucket: 'teacher-dashboard-flutterfire.firebasestorage.app',
    databaseURL: 'https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com',
  );
}