name: Validate Secrets
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly validation
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Secrets
        run: |
          REQUIRED_SECRETS=(
            "FIREBASE_API_KEY"
            "FIREBASE_PROJECT_ID"
            "FIREBASE_MESSAGING_SENDER_ID"
            "FIREBASE_STORAGE_BUCKET"
            "FIREBASE_AUTH_DOMAIN"
            "FIREBASE_DATABASE_URL"
            "FIREBASE_APP_ID_WEB"
            "FIREBASE_VAPID_KEY"
            "FIREBASE_TOKEN"
            "GOOGLE_SIGNIN_CLIENT_ID"
          )
          
          MISSING_SECRETS=()
          
          for secret in "${REQUIRED_SECRETS[@]}"; do
            # Check if secret exists by testing if it's empty when referenced
            if [ -z "${!secret:-}" ]; then
              echo "❌ Missing secret: $secret"
              MISSING_SECRETS+=("$secret")
            else
              echo "✅ Found secret: $secret"
            fi
          done
          
          if [ ${#MISSING_SECRETS[@]} -gt 0 ]; then
            echo ""
            echo "❌ VALIDATION FAILED"
            echo "Missing ${#MISSING_SECRETS[@]} required secret(s):"
            printf '%s\n' "${MISSING_SECRETS[@]}"
            echo ""
            echo "Add these secrets in: Settings → Secrets and variables → Actions"
            exit 1
          else
            echo ""
            echo "✅ All required secrets are configured!"
          fi
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_APP_ID_WEB: ${{ secrets.FIREBASE_APP_ID_WEB }}
          FIREBASE_VAPID_KEY: ${{ secrets.FIREBASE_VAPID_KEY }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_SIGNIN_CLIENT_ID: ${{ secrets.GOOGLE_SIGNIN_CLIENT_ID }}

      - name: Validate Secret Format
        run: |
          # Basic validation of secret formats
          
          # Check PROJECT_ID format
          if [[ ! "${{ secrets.FIREBASE_PROJECT_ID }}" =~ ^[a-z0-9-]+$ ]]; then
            echo "❌ FIREBASE_PROJECT_ID has invalid format"
            exit 1
          fi
          
          # Check API_KEY format (should be alphanumeric with dashes/underscores)
          if [[ ! "${{ secrets.FIREBASE_API_KEY }}" =~ ^[A-Za-z0-9_-]+$ ]]; then
            echo "❌ FIREBASE_API_KEY has invalid format"
            exit 1
          fi
          
          # Check CLIENT_ID format
          if [[ ! "${{ secrets.GOOGLE_SIGNIN_CLIENT_ID }}" =~ ^[0-9]+-[a-z0-9]+\.apps\.googleusercontent\.com$ ]]; then
            echo "❌ GOOGLE_SIGNIN_CLIENT_ID has invalid format"
            exit 1
          fi
          
          echo "✅ All secrets have valid formats"