name: CI - Code Quality & Dead Code Detection
on:
  pull_request:
  push:
    branches: [ main, master ]
    
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  
jobs:
  validate:
    name: Validate & Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

      - name: Check formatting
        run: dart format --set-exit-if-changed .
      
      - name: Install dead_code_analyzer
        run: dart pub global activate dead_code_analyzer
        
      - name: Run dead code analysis
        run: |
          echo "=== Dead Code Analysis Report ===" 
          echo "Analyzing for unused classes, functions, and variables..."
          echo "Analyzing only lib/ directory (skipping android, ios, web, etc.)"
          dead_code_analyzer -p lib --no-progress --analyze-functions --max-unused 50 || true
        continue-on-error: true
        
      - name: Save dead code report
        if: github.event_name == 'pull_request'
        run: |
          dead_code_analyzer -p lib --no-progress --analyze-functions --max-unused 100 -o . > dead_code_report.txt 2>&1 || true
          echo "### Dead Code Analysis Results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat dead_code_report.txt | head -100 >> $GITHUB_STEP_SUMMARY || echo "No dead code report generated" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
