name: Windows Release

on:
  push:
    tags:
      - 'windows-v*'
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows Desktop
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            # Extract version from tag
            TAG="${{ github.ref_name }}"
            VERSION=${TAG#v}
            VERSION=${VERSION#windows-v}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows build
        run: flutter config --enable-windows-desktop

      - name: Build Windows Desktop
        run: flutter build windows --release --build-name=${{ steps.get_version.outputs.version }} --build-number=${{ github.run_number }}

      - name: Create portable ZIP
        shell: bash
        run: |
          cd build/windows/x64/runner/Release
          # This folder contains fermi.exe and all required DLLs and data
          7z a -tzip "../../../../../Fermi-Windows-v${{ steps.get_version.outputs.version }}.zip" .
          cd ../../../../../
          ls -la *.zip
          echo "Created portable ZIP with all required files"

      - name: Upload portable ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: Fermi-Windows-v${{ steps.get_version.outputs.version }}.zip

  create-release:
    name: Create GitHub Release
    needs: build-windows
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-portable
          path: ./

      - name: Get version from tag
        id: get_version
        run: |
          TAG="${{ github.ref_name }}"
          VERSION=${TAG#v}
          VERSION=${VERSION#windows-v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Fermi Windows v${{ steps.get_version.outputs.version }}
          body: |
            ## Fermi Education Platform - Windows Release v${{ steps.get_version.outputs.version }}
            
            ### 📦 Download
            Download `Fermi-Windows-Portable.zip` and extract to any folder. No installation required.
            
            ### System Requirements
            - Windows 10 version 1809 or higher
            - Windows 11 (all versions)
            - x64 architecture
            - 200 MB free disk space
            
            ### Features
            - ✅ Google Sign-In support
            - ✅ Apple Sign-In support
            - ✅ Real-time messaging
            - ✅ File upload/download
            - ✅ Push notifications
            - ✅ Offline support
            
            ### Known Issues
            - Some antivirus software may flag the unsigned executable. This is a false positive.
            - For code signing in future releases, we'll need an EV certificate.
          files: |
            Fermi-Windows-v${{ steps.get_version.outputs.version }}.zip
          draft: false
          prerelease: false