name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      # Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      - name: Generate macOS ephemeral files
        run: flutter build macos --debug

      # Run Flutter analyze
      - name: Analyze code
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test --coverage

      # Build the Flutter project
      - name: Build
        run: |
          flutter build web
          flutter build apk --debug

