name: iOS Build CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'lib/**'
      - 'ios/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - '.github/workflows/ios-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'ios/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.32.7'
  XCODE_VERSION: '15.2'
  IOS_DEPLOYMENT_TARGET: '16.0'
  
jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      
      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: flutter-${{ runner.os }}-${{ env.FLUTTER_VERSION }}
          restore-keys: |
            flutter-${{ runner.os }}-
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      # Disabled CocoaPods cache to ensure clean builds
      # - name: Cache CocoaPods
      #   uses: actions/cache@v3
      #   with:
      #     path: ios/Pods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-
      
      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      
      - name: Install dependencies
        run: |
          flutter pub get
          
      - name: Verify flutter_webrtc patch
        run: |
          if [ -f scripts/patch_flutter_webrtc.sh ]; then
            echo "flutter_webrtc patch script found"
            chmod +x scripts/patch_flutter_webrtc.sh
          fi
          
      - name: Update CocoaPods
        run: |
          gem install cocoapods
          pod --version
          
      - name: Clean iOS build environment
        working-directory: ios
        run: |
          # Remove any existing pods and lock files
          rm -rf Pods
          rm -rf .symlinks
          rm -f Podfile.lock
          rm -rf ~/Library/Caches/CocoaPods
          
          # Clean pod cache
          pod cache clean --all
          
          # Deintegrate existing pods
          pod deintegrate || true
          
      - name: Pod install
        working-directory: ios
        run: |
          # Update pod repo
          pod repo update --verbose
          
          # Install pods with verbose output
          pod install --repo-update --verbose
          
          # Verify GoogleUtilities installation
          echo "Checking for GoogleUtilities_NSData module..."
          find Pods -name "*GoogleUtilities*" -type d | head -20
          
      - name: Create module maps for Firebase pods
        working-directory: ios
        run: |
          chmod +x create_module_maps.sh
          ./create_module_maps.sh
      
      - name: Build iOS (no signing)
        run: |
          flutter build ios --release --no-codesign --no-tree-shake-icons \
            --dart-define=CI_BUILD=true \
            --build-number=${{ github.run_number }}
      
      - name: Compress build artifacts
        if: success()
        run: |
          cd build/ios/iphoneos
          tar -czf ios-build.tar.gz Runner.app
          mv ios-build.tar.gz ../../../
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ios-build-${{ github.sha }}
          path: ios-build.tar.gz
          retention-days: 7
          
      - name: Upload Podfile.lock
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: podfile-lock-${{ github.sha }}
          path: ios/Podfile.lock
          retention-days: 7
          
      - name: Report build size
        if: success()
        run: |
          echo "### Build Size Report" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Size |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|------|" >> $GITHUB_STEP_SUMMARY
          echo "| App Size | $(du -sh build/ios/iphoneos/Runner.app | cut -f1) |" >> $GITHUB_STEP_SUMMARY
          echo "| Compressed | $(ls -lh ios-build.tar.gz | awk '{print $5}') |" >> $GITHUB_STEP_SUMMARY