name: Deploy Web App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.x'  # Adjust based on your Flutter version

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true
        
    - name: Setup Node.js for Firebase CLI
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Create .env file
      run: |
        cat << EOF > .env
        FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}
        FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }}
        FIREBASE_APP_ID_IOS=${{ secrets.FIREBASE_APP_ID_IOS }}
        IOS_BUNDLE_ID=${{ secrets.IOS_BUNDLE_ID }}
        GOOGLE_CLOUD_PROJECT=${{ secrets.GOOGLE_CLOUD_PROJECT }}
        FIREBASE_VAPID_KEY=${{ secrets.FIREBASE_VAPID_KEY }}
        EOF
        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Run code generation
      run: flutter pub run build_runner build --delete-conflicting-outputs
      
    - name: Run tests
      run: flutter test
      
    - name: Build web app
      run: flutter build web --web-renderer canvaskit --release
      
    - name: Install Functions dependencies
      run: |
        cd functions
        npm ci
        
    - name: Build Functions
      run: |
        cd functions
        npm run build
        
    - name: Deploy to Firebase Hosting
      if: github.ref == 'refs/heads/main'
      run: |
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}
        
    - name: Deploy Firebase Functions
      if: github.ref == 'refs/heads/main'
      run: |
        firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}
        
    - name: Deploy Firestore Rules
      if: github.ref == 'refs/heads/main'
      run: |
        firebase deploy --only firestore:rules --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}