name: Deploy Web App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.x'  # Adjust based on your Flutter version

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true
        
    - name: Setup Node.js for Firebase CLI
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      

        
    - name: Get Flutter dependencies
      run: flutter pub get
      
    - name: Run code generation
      run: flutter pub run build_runner build --delete-conflicting-outputs
      
    - name: Run tests
      run: flutter test
      
    - name: Build web app
      run: |
        flutter build web --web-renderer canvaskit --release \
          --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
          --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
          --dart-define=FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }} \
          --dart-define=FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
          --dart-define=FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} \
          --dart-define=FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }} \
          --dart-define=FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}
      
    - name: Install Functions dependencies
      run: |
        cd functions
        npm ci
        
    - name: Build Functions
      run: |
        cd functions
        npm run build
        
    - name: Deploy to Firebase Hosting
      if: github.ref == 'refs/heads/main'
      run: |
        firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Deploy Firebase Functions
      if: github.ref == 'refs/heads/main'
      run: |
        firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Deploy Firestore Rules
      if: github.ref == 'refs/heads/main'
      run: |
        firebase deploy --only firestore:rules --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}