// Firebase configuration loaded from environment
// This file is auto-generated by scripts/generate-firebase-config.js
// DO NOT edit manually - run the generation script instead

const firebaseConfig = {
  apiKey: "AIzaSyD_nLVRdyd6ZlIyFrRGCW5IStXnM2-uUac",
  authDomain: "teacher-dashboard-flutterfire.firebaseapp.com",
  projectId: "teacher-dashboard-flutterfire",
  storageBucket: "teacher-dashboard-flutterfire.firebasestorage.app",
  messagingSenderId: "218352465432",
  appId: "1:218352465432:web:6e1c0fa4f21416df38b56d",
  databaseURL: "https://teacher-dashboard-flutterfire-default-rtdb.firebaseio.com"
};